# Generated by Django 5.2.7 on 2025-11-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on_the_way', 'On the way'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='on_the_way', max_length=20),
        ),
    ]
