# Generated by Django 5.2.8 on 2026-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qr', 'QR'), ('cash', 'Cash')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10),
        ),
    ]
