# Generated by Django 5.2.8 on 2026-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0004_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qr_payment', 'QR Payment'), ('cash', 'Cash')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending_verification', 'Pending Verification'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
    ]
