# Generated by Django 5.2.8 on 2026-01-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproject', '0006_profile_location_profile_phone_profile_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
